[package]
name = 'a5r'
publish = false
version = '0.1.0'
edition = '2021'
rust-version = '1.65'

[lib]
crate-type = [ 'staticlib' ]
name = 'a5r'

[dependencies]
extendr-api = '0.8.1'
a5 = '0.6.2'

[profile.release]
lto = true
codegen-units = 1
